//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GridLayout.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdData
    {
        public int Id { get; set; }
        public string User_Id { get; set; }
        public string City_Id { get; set; }
        public string Locality_Id { get; set; }
        public string Category_Id { get; set; }
        public string SubCategory_Id { get; set; }
        public string AdType_Id { get; set; }
        public string Ad_Title { get; set; }
        public string Ad_Description { get; set; }
        public string Ad_Photo { get; set; }
        public string Mobile { get; set; }
    }
}
