//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GridLayout.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdData
    {
        public int Id { get; set; }
        public string User_Id { get; set; }
        public string UserName { get; set; }
        public int City_Id { get; set; }
        public Nullable<int> Locality_Id { get; set; }
        public int Category_Id { get; set; }
        public Nullable<int> AdType_Id { get; set; }
        public string Ad_Title { get; set; }
        public string Ad_Description { get; set; }
        public string Ad_Photo { get; set; }
        public string Mobile { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    
        public virtual AdType AdType { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Category Category { get; set; }
        public virtual City City { get; set; }
    }
}
