//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GridLayout.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdType
    {
        public AdType()
        {
            this.AdDatas = new HashSet<AdData>();
        }
    
        public int ID { get; set; }
        public string AdTypeName { get; set; }
    
        public virtual ICollection<AdData> AdDatas { get; set; }
    }
}
