//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GridLayout.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDetail
    {
        public int Id { get; set; }
        public string User_Id { get; set; }
        public string User_Name { get; set; }
        public string User_Address { get; set; }
        public string User_Photo { get; set; }
        public string Mobile { get; set; }
    }
}
